### PR TITLE
Update Ocarina of Time.psm1 - Forgot a dialogue, also text corrections and improvements...

### PR DESCRIPTION
**Pull request by GoldenMariaNova**
Well, sorry with this again, but I forgot a dialogue when I did the last GC Scheme update.

Also check the replies for an extended description.

### CODE REVIEW

**Comment by GoldenMariaNova** [comment]
> snips

Since I did the **MM** one with references before , I decided to do it for **OOT** too, so now, it's a 1:1 GC text change conversion from the **Collector's Edition** for now on.

As a bonus, the "MM Milk" text option should change the _**"You got XXX"**_ to the appropriate description.

**Comment by GoldenMariaNova** [comment]
> > snips
> 
> Since I did the **MM** one with references before , I decided to do it for **OOT** too, so now, it's a 1:1 GC text change conversion from the **Collector's Edition** for now on.
> 
> As a bonus, the "MM Milk" text option should change the _**"You got XXX"**_ to the appropriate description when getting... **Milk**.

Update: I also fixed some patches with **Scene Editor** not working.

**Comment by Admentus64** [comment]
"Dampè's Grave & Windwill" is still misstyped.

The previous name did work before, until I pushed a fix to correct the typo as part of another project.

**Comment by GoldenMariaNova** [comment]
> snips

Yeah, that's what I got to have done last minute changes too fast.

Anyways, the _**"Milk"**_ thing is for one dialogue only, just like **MM** did it : for when you got an item. The _**"MM Fairy"**_ don't need it, as it essentially the same already.

Anyways, I hope this works.

**Pull request merged**
