### PR TITLE
Added Lake Hylia Owl to "Remove Owls" option

### PR DESCRIPTION
**Pull request by GoldenMariaNova**
I added the Lake Hylia **Owl** to "**_Remove Owls_**", as he don't really add anything, than a easily missable "shortcut" that you can literally take somewhere else, like going back on the path to **Zora's Fountain** with the waterfalls,  making this owl redundant. Also, 90% of players in general, don't even use it anyways. I should have thought about this sooner.

Now, the ONLY really useful owl is at "**Death Mountain**". Otherwise, a **Gold Skultulla** would be inaccessible, breaking the game. So now, he's only at the top of the latter for the reminder of the entire game.

Also, I added the C-Up Button dialogue for GC Scheme, and I **HOPE** it's the last time I ever touch this. That's it.

### CODE REVIEW

**Review by Admentus64 — CHANGES_REQUESTED** [review]
I am refusing the Owl changle. The Remove Owl option is meant to remove all Owls that annoy Link with forced tutorial interuptions. The Owl from Lake Hylia isn't one of those.

As for the text change. Why is the word "Button" itself removed? What has that to do with being part of the N64 vs GameCube controller layout? Maybe it's better reserved for the upcoming Restore Text rework?

**Comment by GoldenMariaNova** [comment]
> snips

Well, the **Lake Hylia** Owl should be it's own option now.

As the **C-Up** "Button" text being removed, well... In **GC** **OOT**, none of the **C-Up**, **C-Down**, **C-Left** and **C-Right** are referred as "buttons", they are just text icons, since **Gamecube** has a **C-Stick** and not four buttons like the **N64** controller.

Also, **NO**, your **Restore Text** should still have the unaltered **N64** scheme, for maximum flexibility.

**Comment by Admentus64** [comment]
> Well, the Lake Hylia Owl should be it's own option now.

Looks good. But it adds too much clutter to the GUI. Changing the existing option into a dropdown menu would be cleaner, aka, Faster Block Pushing style.

> As the C-Up "Button" text being removed, well... In GC OOT, none of the C-Up, C-Down, C-Left and C-Right are referred as "buttons", they are just text icons, since Gamecube has a C-Stick and not four buttons, like the N64 controller.

> If anything, it's not "removed", just modified to show the icon only, as based on OOT Collector Edition and Master Quest.

Alright. At least it's consistent. I can accept it for now.

> Also, **NO**, your **Restore Text** should still have the unaltered **N64** scheme, for maximum flexibility.

That's up to me.



Please resolve issues for acceptance. Looks fine otherwise.

**Comment by Admentus64** [comment]
Why it is forced? And what is it for?

Otherwise looks like it's on the right track.

**Comment by GoldenMariaNova** [comment]
> snips

I removed the extra **-Force** and **-Safe** lines, as it was part of the old line. Now it should be fully functional.

**Comment by Admentus64** [comment]
Looks fine now. I approve it later.

Your branch might not have been up to date with the master since of those lines. But for now it isn't an issue.

Make sure to rebase when starting a new PR next time.

**Comment by GoldenMariaNova** [comment]
> snips

Done. Forgot about it.

**Review by Admentus64 — APPROVED** [review]
Approved

**Pull request merged**
