### PR TITLE
MM - Code fix for text commands

### PR DESCRIPTION
**Pull request by Qlonever**
Adds a patch option for Majora's Mask that fixes instant text, delays, and sound effects not working in text boxes sometimes. It's a code fix, so I also removed the one text-side fix for this issue. It only fixed one broken sound effect out of dozens of affected text boxes anyway. I played through the entire game with this patch enabled and encountered no issues.

### CODE REVIEW

**Review by Admentus64 — CHANGES_REQUESTED** [review]
PPF patches won't be accepted for text changes.

Please rework your patch to make use of the Text Editor API.

**Comment by Qlonever** [comment]
> PPF patches won't be accepted for text changes.
> 
> Please rework your patch to make use of the Text Editor API.

The PPF patch only includes code edits. The code affects text boxes, but no actual text content was changed.

**Comment by Admentus64** [comment]
Closing this pull request due to failing to meet requested changes.

**Comment by Admentus64** [comment]
Reopened again as part of the clarification which was on the Discord server.

**Review by Admentus64 — APPROVED** [review]
Approved

**Pull request merged**
