### PR TITLE
Update Ocarina of Time.psm1

### PR DESCRIPTION
**Pull request by GoldenMariaNova**
Corrected Power Bracelet typos.

### CODE REVIEW

**Comment by Admentus64** [comment]
I don't see the point of these changes?

**Comment by GoldenMariaNova** [comment]
> I don't see the point of these changes?

There was multiple errors because it didn't either patch the file because it has the wrong directory, or one even patched the "**Hero bow**" label.

Now everything should be fine. It got verified anyways.

Just let me correct the text entry now.

**Comment by Admentus64** [comment]
I rename the files then. Probably forget to do so. I look into this myself.

**Comment by Admentus64** [comment]
Applied with hotfix 1

**Pull request closed without merging**
