### PR TITLE
Update Majora's Mask.psm1  : GC Scheme Text

### PR DESCRIPTION
**Pull request by GoldenMariaNova**
This one was pathetically easy to do, compared to the highly contextual OOT ones.

Anyways, it's done.

### CODE REVIEW

**Comment by Admentus64** [comment]
This is wrong. Text changes go into ByteTextOptions. Not into TextOptions. Won't work.

Code otherwise looks fine. Just in the wrong place.

**Review by Admentus64 — CHANGES_REQUESTED** [review]
--- Request changes ---
Move changes into ByteTextOptions

**Comment by GoldenMariaNova** [comment]
> snips

**Ouch**. I should have noticed that. It's fixed now.

**Comment by Admentus64** [comment]
Looks fine now.

**Pull request merged**
